name: masonex
environment:
  sdk: ">=3.11.1 <4.0.0"
dev_dependencies:
  melos: ^7.4.1

melos:
  packages:
    - packages/*

  scripts:
    publish:masonex:
      run: melos publish --dry-run --scope="masonex" --scope="masonex_cli" --scope="masonex_annotations"
      description: |
        Publish the masonex packages (masonex, masonex_cli, and masonex_annotations).