name: taskflow_hooked_task_hooks
description: Hooks for the taskflow_hooked_task brick.

environment:
  sdk: ^3.5.4

dependencies:
  masonex: any

dependency_overrides:
  mason_api:
    path: ../../../../packages/mason_api
  mason_logger:
    path: ../../../../packages/mason_logger
  masonex:
    path: ../../../../packages/masonex
  mustachex:
    path: ../../../../packages/mustachex
