/// Generated by the `task` brick declared in masonex.yaml.
class {{name.pascalCase()}} {
  const {{name.pascalCase()}}({required this.id, required this.title});
  final String id;
  final String title;
}
