@pragma('masonex:header', {
  Task: '{{name.pascalCase()}}',
})
library;

/// Generated by the `task` brick declared in masonex.yaml.
class Task {
  const Task({required this.id, required this.title});
  final String id;
  final String title;
}
