name: build_utils
description: A bunch of classes, helpers, generators and things to work with
  package:build with ease
version: 0.1.0
homepage: https://www.gitlab.com/Rodsevich/build_utils

environment:
  sdk: '^3.11.0'

dependencies:
  analysis_utils:
    path: ../analysis_utils
  analyzer: ^6.4.1
  build: ^2.4.1
  build_test: ^2.2.0
  dart_style: ^2.3.6
  glob: ^2.1.2
  meta: ^1.11.0
  path: ^1.9.0
  source_gen: ^1.5.0

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^5.1.1
  test: ^1.25.0
