name: random_color_hooks

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  masonex: any

dependency_overrides:
  masonex:
    path: ../../../packages/masonex
  mustachex:
    path: ../../../packages/mustachex
  mason_logger:
    path: ../../../packages/mason_logger
