name: pub_score

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  verify_pub_score:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: axel-op/dart-package-analyzer@v3
        id: pub_score
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Pub Score
        env:
          TOTAL: ${{ steps.pub_score.outputs.total }}
        run: 'if (($TOTAL < 120)) then echo "pub score: $TOTAL is below 120" exit 1'
