name: pub_score

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  verify_pub_score:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: |
          dart pub get
          dart pub global activate pana

      - name: Verify Pub Score
        run: |
          SCORE=$(pana . --no-warning | sed -n "s/.*Points: \(\[0-9]+\)*/\1/p")
          echo "Pub Score: $SCORE"
